import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { getDbaServicesAccounts } from '../lib/dbasvcsapi'
import AccountTable from '../components/accounts_table'
import { useState } from 'react';
import Toast from 'react-bootstrap/Toast'
import ToastContainer from 'react-bootstrap/ToastContainer'

export default function Home({accounts, error}) {
	const [show, setShow] = useState(false);

  if (error) {
    if (!show) { setShow(true); }
		return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}> 
        <div className="pt-5">
          <ToastContainer className="pt-5" position="top-end">
            <Toast onClose={() => setShow(false)} show={show} delay={3000} autohide>
              <Toast.Header>
                <strong className="me-auto">Bootstrap</strong>
                <small>1 sec ago</small>
              </Toast.Header>
              <Toast.Body>Accounts get failed: {error}</Toast.Body>
            </Toast>
          </ToastContainer>
        </div>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>
		)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}> 
        <AccountTable accountsData={accounts}></AccountTable>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getServerSideProps(context) {

	let accounts = null
  try {
    accounts = await getDbaServicesAccounts(process.env.DBASVCSAPI_URL + '/accounts', process.env.DBASVCSAPI_ADMIN_KEY)
  } catch(e) {
		console.log(`failed to get accounts: ${e}`);
		return { 
			props: {
				error: e.message
			}
		};
	}

	if (!accounts || (accounts && accounts.length == 0)) {
    console.log("returning no data")
	  return { props: {} }
  }
  
  return {
    props: {
      accounts: accounts
    },
  };
}